//! Conversation types shared by the engine, the tool runtime, and the renderer.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    User,
    Assistant,
    /// Carries a tool result back to the model.
    Tool,
}

/// One piece of a message. A plain text turn is a single [`Part::Text`]; a
/// vision turn interleaves text and images in the order the user supplied them.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Part {
    Text { text: String },
    Image { image: ImageSource },
}

/// Where an image came from. Remote images are fetched and local ones read at
/// prompt-build time, not here, so constructing a message never does I/O.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "source", rename_all = "snake_case")]
pub enum ImageSource {
    Path { path: PathBuf },
    Url { url: String },
    /// Raw bytes, e.g. pasted from the clipboard. Base64 on the wire.
    Bytes {
        #[serde(with = "b64")]
        bytes: Vec<u8>,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        mime: Option<String>,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub role: Role,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub content: Vec<Part>,

    /// Reasoning emitted before the visible answer. Kept separate so it can be
    /// rendered differently, or dropped from the context on the next turn.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thinking: Option<String>,

    /// Tool calls the assistant requested this turn.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tool_calls: Vec<ToolCall>,

    /// For [`Role::Tool`], the call this message answers.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
}

impl Message {
    pub fn system(text: impl Into<String>) -> Self {
        Self::text(Role::System, text)
    }
    pub fn user(text: impl Into<String>) -> Self {
        Self::text(Role::User, text)
    }
    pub fn assistant(text: impl Into<String>) -> Self {
        Self::text(Role::Assistant, text)
    }

    fn text(role: Role, text: impl Into<String>) -> Self {
        Self {
            role,
            content: vec![Part::Text { text: text.into() }],
            thinking: None,
            tool_calls: Vec::new(),
            tool_call_id: None,
        }
    }

    /// A tool result addressed to the call that produced it.
    pub fn tool_result(call_id: impl Into<String>, body: impl Into<String>) -> Self {
        Self {
            role: Role::Tool,
            content: vec![Part::Text { text: body.into() }],
            thinking: None,
            tool_calls: Vec::new(),
            tool_call_id: Some(call_id.into()),
        }
    }

    pub fn with_image(mut self, src: ImageSource) -> Self {
        self.content.push(Part::Image { image: src });
        self
    }

    /// Concatenated text parts, ignoring images.
    pub fn text_content(&self) -> String {
        let mut out = String::new();
        for p in &self.content {
            if let Part::Text { text } = p {
                out.push_str(text);
            }
        }
        out
    }

    pub fn images(&self) -> impl Iterator<Item = &ImageSource> {
        self.content.iter().filter_map(|p| match p {
            Part::Image { image } => Some(image),
            _ => None,
        })
    }

    pub fn has_images(&self) -> bool {
        self.images().next().is_some()
    }
}

/// A tool invocation requested by the model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolCall {
    /// Correlates the call with its result. Generated by us when the model's
    /// output format does not carry one.
    pub id: String,
    pub name: String,
    /// Arguments as a JSON object, already validated against the tool's schema.
    pub arguments: serde_json::Value,
}

/// A tool as advertised to the model, mirroring the standard function-calling
/// shape so it drops into most chat templates unchanged.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolSpec {
    pub name: String,
    #[serde(default)]
    pub description: String,
    /// JSON Schema for the arguments object.
    pub input_schema: serde_json::Value,
    /// JSON Schema for the result. Not sent to the model, but used to validate
    /// what a tool returns before it enters the context.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_schema: Option<serde_json::Value>,
}

/// Base64, shared so front ends can decode what a browser hands them.
pub mod b64 {
    use serde::{Deserialize, Deserializer, Serializer};

    const CHARS: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    pub fn encode(bytes: &[u8]) -> String {
        let mut out = String::with_capacity((bytes.len() + 2) / 3 * 4);
        for c in bytes.chunks(3) {
            let b = [c[0], *c.get(1).unwrap_or(&0), *c.get(2).unwrap_or(&0)];
            let n = u32::from_be_bytes([0, b[0], b[1], b[2]]);
            for i in 0..4 {
                if i <= c.len() {
                    out.push(CHARS[(n >> (18 - 6 * i) & 0x3f) as usize] as char);
                } else {
                    out.push('=');
                }
            }
        }
        out
    }

    pub fn decode(s: &str) -> Result<Vec<u8>, &'static str> {
        let mut acc = 0u32;
        let mut bits = 0u8;
        let mut out = Vec::with_capacity(s.len() / 4 * 3);
        for ch in s.bytes() {
            if ch == b'=' || ch.is_ascii_whitespace() {
                continue;
            }
            let v = CHARS.iter().position(|&c| c == ch).ok_or("invalid base64 character")? as u32;
            acc = acc << 6 | v;
            bits += 6;
            if bits >= 8 {
                bits -= 8;
                out.push((acc >> bits) as u8);
            }
        }
        Ok(out)
    }

    pub fn serialize<S: Serializer>(v: &[u8], s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&encode(v))
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<u8>, D::Error> {
        let s = String::deserialize(d)?;
        decode(&s).map_err(serde::de::Error::custom)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn text_content_skips_images() {
        let m = Message::user("look at this")
            .with_image(ImageSource::Path { path: "/tmp/a.png".into() });
        assert_eq!(m.text_content(), "look at this");
        assert!(m.has_images());
        assert_eq!(m.images().count(), 1);
    }

    #[test]
    fn messages_round_trip_as_json() {
        let m = Message::user("hi").with_image(ImageSource::Bytes {
            bytes: vec![0, 1, 2, 250, 255],
            mime: Some("image/png".into()),
        });
        let s = serde_json::to_string(&m).unwrap();
        let back: Message = serde_json::from_str(&s).unwrap();
        match back.images().next().unwrap() {
            ImageSource::Bytes { bytes, mime } => {
                assert_eq!(bytes, &[0, 1, 2, 250, 255]);
                assert_eq!(mime.as_deref(), Some("image/png"));
            }
            other => panic!("wrong variant: {other:?}"),
        }
    }

    #[test]
    fn base64_handles_every_padding_case() {
        for n in 0..16usize {
            let data: Vec<u8> = (0..n).map(|i| (i * 37 + 11) as u8).collect();
            let enc = b64::encode(&data);
            assert_eq!(enc.len() % 4, 0, "encoding must be padded: {enc:?}");
            assert_eq!(b64::decode(&enc).unwrap(), data, "round trip failed at len {n}");
        }
    }
}
