//! What a workflow is.
//!
//! A flow is steps and the wires between them, and nothing else — no runtime
//! state, no cached outputs. It is what the canvas edits and what gets stored,
//! so it has to survive a round trip through JSON unchanged, including the
//! parts this crate does not understand: a node's `params` are whatever that
//! kind of node needs, and are carried through untouched.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet, HashMap};

/// The port a normal step emits on.
pub const OUT: &str = "out";
/// The two ports a condition emits on.
pub const YES: &str = "yes";
pub const NO: &str = "no";

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[serde(default)]
pub struct Flow {
    pub name: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    pub description: String,
    pub nodes: Vec<Node>,
    pub edges: Vec<Edge>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Node {
    /// Unique within the flow. Generated by the editor and never reused: it is
    /// what expressions refer to, so renaming a node must not break them.
    pub id: String,
    pub kind: Kind,
    /// What the canvas shows. Free text, and not what expressions use.
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub x: f64,
    #[serde(default)]
    pub y: f64,
    /// Settings for this kind of node, carried through verbatim.
    #[serde(default)]
    pub params: BTreeMap<String, Value>,
}

impl Node {
    pub fn param(&self, key: &str) -> Option<&Value> {
        self.params.get(key)
    }

    pub fn text(&self, key: &str) -> &str {
        self.params.get(key).and_then(|v| v.as_str()).unwrap_or("")
    }

    /// The label a run record shows. Falls back to the id, which is always
    /// there — an unnamed node in a failed run must still be identifiable.
    pub fn label(&self) -> &str {
        if self.name.trim().is_empty() { &self.id } else { self.name.trim() }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Kind {
    /// Starts when someone presses run.
    Manual,
    /// Starts on a timer.
    Schedule,
    /// Starts when something calls its URL.
    Webhook,
    /// Calls one of the installed tools. This is what makes every tool a
    /// connector without a second plugin system existing to describe them.
    Tool,
    /// Asks the model something.
    Agent,
    /// Sends the run down one of two ports.
    Condition,
    /// Builds a piece of text from earlier outputs.
    Text,
}

impl Kind {
    /// Whether this kind starts a run rather than continuing one.
    pub fn is_trigger(self) -> bool {
        matches!(self, Self::Manual | Self::Schedule | Self::Webhook)
    }

    /// The ports this kind can emit on.
    pub fn ports(self) -> &'static [&'static str] {
        match self {
            Self::Condition => &[YES, NO],
            _ => &[OUT],
        }
    }
}

impl std::fmt::Display for Kind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self {
            Self::Manual => "manual",
            Self::Schedule => "schedule",
            Self::Webhook => "webhook",
            Self::Tool => "tool",
            Self::Agent => "agent",
            Self::Condition => "condition",
            Self::Text => "text",
        };
        f.write_str(name)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Edge {
    pub from: String,
    pub to: String,
    /// Which of the source's ports this leaves by.
    #[serde(default = "out_port")]
    pub port: String,
}

fn out_port() -> String {
    OUT.to_string()
}

/// Why a flow cannot be run.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum Invalid {
    #[error("two steps share the id `{0}`")]
    DuplicateId(String),
    #[error("a wire starts at `{0}`, which is not a step")]
    NoSuchSource(String),
    #[error("a wire ends at `{0}`, which is not a step")]
    NoSuchTarget(String),
    #[error("`{node}` has no port called `{port}`")]
    NoSuchPort { node: String, port: String },
    #[error("`{0}` starts a run, so nothing can lead into it")]
    TriggerHasInput(String),
    #[error("nothing starts this flow: add a trigger")]
    NoTrigger,
    #[error("these steps form a loop: {0}")]
    Cycle(String),
}

impl Flow {
    pub fn node(&self, id: &str) -> Option<&Node> {
        self.nodes.iter().find(|n| n.id == id)
    }

    pub fn triggers(&self) -> impl Iterator<Item = &Node> {
        self.nodes.iter().filter(|n| n.kind.is_trigger())
    }

    /// Every reason this flow cannot run, in the order a person would fix them.
    ///
    /// All of them, not the first: an editor that reports one problem per save
    /// makes fixing three a three-round-trip exercise.
    pub fn problems(&self) -> Vec<Invalid> {
        let mut problems = Vec::new();

        let mut seen = BTreeSet::new();
        for node in &self.nodes {
            if !seen.insert(node.id.as_str()) {
                problems.push(Invalid::DuplicateId(node.id.clone()));
            }
        }

        let ids: BTreeSet<&str> = self.nodes.iter().map(|n| n.id.as_str()).collect();
        for edge in &self.edges {
            if !ids.contains(edge.from.as_str()) {
                problems.push(Invalid::NoSuchSource(edge.from.clone()));
                continue;
            }
            if !ids.contains(edge.to.as_str()) {
                problems.push(Invalid::NoSuchTarget(edge.to.clone()));
                continue;
            }
            if let Some(from) = self.node(&edge.from) {
                if !from.kind.ports().contains(&edge.port.as_str()) {
                    problems.push(Invalid::NoSuchPort {
                        node: edge.from.clone(),
                        port: edge.port.clone(),
                    });
                }
            }
            if let Some(to) = self.node(&edge.to) {
                if to.kind.is_trigger() {
                    problems.push(Invalid::TriggerHasInput(edge.to.clone()));
                }
            }
        }

        if self.triggers().next().is_none() {
            problems.push(Invalid::NoTrigger);
        }

        // Only worth looking for once the wires are known to be sound;
        // a cycle report about steps that do not exist helps nobody.
        if problems.is_empty() {
            if let Err(loop_) = self.order() {
                problems.push(loop_);
            }
        }
        problems
    }

    pub fn is_valid(&self) -> bool {
        self.problems().is_empty()
    }

    /// The steps in an order where every step comes after the ones feeding it.
    ///
    /// Kahn's algorithm, taking ready nodes in the order they appear in the
    /// flow rather than in whatever order a hash map yields. Two runs of the
    /// same flow must visit steps in the same order, or a run log is not
    /// comparable with the one before it.
    pub fn order(&self) -> Result<Vec<&Node>, Invalid> {
        let mut incoming: HashMap<&str, usize> = self.nodes.iter().map(|n| (n.id.as_str(), 0)).collect();
        for edge in &self.edges {
            if let Some(count) = incoming.get_mut(edge.to.as_str()) {
                *count += 1;
            }
        }

        let mut ready: Vec<&Node> =
            self.nodes.iter().filter(|n| incoming[n.id.as_str()] == 0).collect();
        let mut out = Vec::with_capacity(self.nodes.len());

        while let Some(node) = ready.first().copied() {
            ready.remove(0);
            out.push(node);
            // Freed nodes are appended, then the whole queue is re-sorted into
            // flow order, so the traversal is a function of the flow alone.
            for edge in self.edges.iter().filter(|e| e.from == node.id) {
                if let Some(count) = incoming.get_mut(edge.to.as_str()) {
                    *count -= 1;
                    if *count == 0 {
                        if let Some(freed) = self.node(&edge.to) {
                            ready.push(freed);
                        }
                    }
                }
            }
            ready.sort_by_key(|n| self.nodes.iter().position(|m| m.id == n.id));
        }

        if out.len() != self.nodes.len() {
            let stuck: Vec<&str> = self
                .nodes
                .iter()
                .filter(|n| !out.iter().any(|o| o.id == n.id))
                .map(|n| n.id.as_str())
                .collect();
            return Err(Invalid::Cycle(stuck.join(" → ")));
        }
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn node(id: &str, kind: Kind) -> Node {
        Node {
            id: id.into(),
            kind,
            name: String::new(),
            x: 0.0,
            y: 0.0,
            params: BTreeMap::new(),
        }
    }

    fn edge(from: &str, to: &str) -> Edge {
        Edge { from: from.into(), to: to.into(), port: OUT.into() }
    }

    fn flow(nodes: Vec<Node>, edges: Vec<Edge>) -> Flow {
        Flow { name: "test".into(), description: String::new(), nodes, edges }
    }

    #[test]
    fn a_straight_line_runs_in_order() {
        let f = flow(
            vec![node("a", Kind::Manual), node("b", Kind::Tool), node("c", Kind::Agent)],
            vec![edge("a", "b"), edge("b", "c")],
        );
        assert!(f.is_valid(), "{:?}", f.problems());
        let ids: Vec<&str> = f.order().unwrap().iter().map(|n| n.id.as_str()).collect();
        assert_eq!(ids, ["a", "b", "c"]);
    }

    #[test]
    fn a_step_comes_after_everything_feeding_it() {
        // Two branches joining: the join must not run before both arms.
        let f = flow(
            vec![
                node("t", Kind::Manual),
                node("left", Kind::Tool),
                node("right", Kind::Tool),
                node("join", Kind::Agent),
            ],
            vec![edge("t", "left"), edge("t", "right"), edge("left", "join"), edge("right", "join")],
        );
        let ids: Vec<&str> = f.order().unwrap().iter().map(|n| n.id.as_str()).collect();
        let at = |id: &str| ids.iter().position(|i| *i == id).unwrap();
        assert!(at("join") > at("left") && at("join") > at("right"), "{ids:?}");
    }

    #[test]
    fn the_order_is_the_same_every_time() {
        // A run log that cannot be compared with the last one is much less
        // useful, and hash iteration order would make that the default.
        let f = flow(
            vec![
                node("t", Kind::Manual),
                node("a", Kind::Tool),
                node("b", Kind::Tool),
                node("c", Kind::Tool),
            ],
            vec![edge("t", "a"), edge("t", "b"), edge("t", "c")],
        );
        let once: Vec<String> = f.order().unwrap().iter().map(|n| n.id.clone()).collect();
        for _ in 0..20 {
            let again: Vec<String> = f.order().unwrap().iter().map(|n| n.id.clone()).collect();
            assert_eq!(once, again);
        }
        assert_eq!(once, ["t", "a", "b", "c"]);
    }

    #[test]
    fn a_loop_is_reported_with_the_steps_in_it() {
        let f = flow(
            vec![node("t", Kind::Manual), node("a", Kind::Tool), node("b", Kind::Tool)],
            vec![edge("t", "a"), edge("a", "b"), edge("b", "a")],
        );
        match f.problems().as_slice() {
            [Invalid::Cycle(which)] => {
                assert!(which.contains('a') && which.contains('b'), "{which}");
            }
            other => panic!("{other:?}"),
        }
    }

    #[test]
    fn a_flow_with_nothing_to_start_it_is_refused() {
        let f = flow(vec![node("a", Kind::Tool)], vec![]);
        assert_eq!(f.problems(), vec![Invalid::NoTrigger]);
    }

    #[test]
    fn a_wire_to_nowhere_is_reported_by_name() {
        let f = flow(vec![node("t", Kind::Manual)], vec![edge("t", "ghost")]);
        assert_eq!(f.problems(), vec![Invalid::NoSuchTarget("ghost".into())]);

        let f = flow(vec![node("t", Kind::Manual)], vec![edge("ghost", "t")]);
        assert_eq!(f.problems(), vec![Invalid::NoSuchSource("ghost".into())]);
    }

    #[test]
    fn every_problem_is_reported_at_once() {
        // One per save turns fixing three into three round trips.
        let f = flow(
            vec![node("a", Kind::Tool), node("a", Kind::Tool)],
            vec![edge("a", "ghost")],
        );
        let problems = f.problems();
        assert!(problems.len() >= 3, "{problems:?}");
        assert!(problems.contains(&Invalid::DuplicateId("a".into())));
        assert!(problems.contains(&Invalid::NoSuchTarget("ghost".into())));
        assert!(problems.contains(&Invalid::NoTrigger));
    }

    #[test]
    fn nothing_may_lead_into_a_trigger() {
        // A trigger with an input reads as a step that runs twice, and there
        // is no sensible thing to do with the data arriving at it.
        let f = flow(
            vec![node("t", Kind::Manual), node("s", Kind::Schedule), node("x", Kind::Tool)],
            vec![edge("t", "x"), edge("x", "s")],
        );
        assert!(f.problems().contains(&Invalid::TriggerHasInput("s".into())));
    }

    #[test]
    fn a_wire_from_a_port_the_step_does_not_have_is_refused() {
        let f = Flow {
            name: "t".into(),
            description: String::new(),
            nodes: vec![node("t", Kind::Manual), node("x", Kind::Tool)],
            edges: vec![Edge { from: "t".into(), to: "x".into(), port: YES.into() }],
        };
        assert!(f.problems().contains(&Invalid::NoSuchPort {
            node: "t".into(),
            port: YES.into()
        }));
    }

    #[test]
    fn a_condition_has_two_ports_and_everything_else_has_one() {
        assert_eq!(Kind::Condition.ports(), &[YES, NO]);
        assert_eq!(Kind::Tool.ports(), &[OUT]);
        assert!(Kind::Manual.is_trigger() && Kind::Webhook.is_trigger());
        assert!(!Kind::Agent.is_trigger());
    }

    #[test]
    fn a_flow_survives_a_round_trip_through_json_unchanged() {
        // The canvas stores what it edits; a field this crate does not know
        // about must come back out.
        let text = r#"{
            "name": "daily",
            "nodes": [{
                "id": "n1", "kind": "tool", "name": "Search", "x": 40.5, "y": -12.0,
                "params": { "tool": "web_search", "arguments": { "query": "{{ t.q }}" } }
            }],
            "edges": [{ "from": "n1", "to": "n1", "port": "out" }]
        }"#;
        let flow: Flow = serde_json::from_str(text).expect("parsing");
        let back: Flow = serde_json::from_str(&serde_json::to_string(&flow).unwrap()).unwrap();
        assert_eq!(flow, back);
        assert_eq!(back.nodes[0].text("tool"), "web_search");
        assert_eq!(back.nodes[0].x, 40.5);
    }

    #[test]
    fn a_wire_with_no_port_named_defaults_to_the_ordinary_one() {
        let edge: Edge = serde_json::from_str(r#"{ "from": "a", "to": "b" }"#).unwrap();
        assert_eq!(edge.port, OUT);
    }

    #[test]
    fn an_unnamed_step_still_has_something_to_call_it() {
        let mut n = node("n1", Kind::Tool);
        assert_eq!(n.label(), "n1");
        n.name = "  Search  ".into();
        assert_eq!(n.label(), "Search");
    }
}
